development:
  email_password: 'Hive@Alveo99'
  email_address: 'alveohive.com'
  email_port: 465
  email_domain: 'alveohive.com'
  email_user_name: 'support@alveohive.com'
  GOOGLE_API_KEY: 'AIzaSyCVPy4OvXyq9bGgTy6vbU7QQN6fRgvjZRY'

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_password: 'Hive@Alveo99'
  email_address: 'alveohive.com'
  email_port: 465
  email_domain: 'alveohive.com'
  email_user_name: 'support@alveohive.com'
  GOOGLE_API_KEY: 'AIzaSyCVPy4OvXyq9bGgTy6vbU7QQN6fRgvjZRY'
