development:
  email_password: ''
  email_address: ''
  email_port: 465
  email_domain: 'alveohive.com'
  email_user_name: ''
  GOOGLE_API_KEY: ''

production:
  secret_key_base: ''
  email_password: ''
  email_address: ''
  email_port: 465
  email_domain: 'alveohive.com'
  email_user_name: ''
  GOOGLE_API_KEY: ''
